<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkfxkrr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkfxkrr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWkfxkrr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWkfxkrr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWkfxkrr\appDevDebugProjectContainer([
    'container.build_hash' => 'Wkfxkrr',
    'container.build_id' => '8e4597b0',
    'container.build_time' => 1589500933,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkfxkrr');
