<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'backlogbundle.calendar_listener' shared service.

include_once $this->targetDirs[3].'\\src\\BacklogBundle\\EventListener\\TaskEventListener.php';

return $this->services['backlogbundle.calendar_listener'] = new \BacklogBundle\EventListener\TaskEventListener(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
