<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'gregwar_captcha.phrase_builder' shared service.

include_once $this->targetDirs[3].'\\vendor\\gregwar\\captcha\\src\\Gregwar\\Captcha\\PhraseBuilderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\gregwar\\captcha\\src\\Gregwar\\Captcha\\PhraseBuilder.php';

return $this->services['gregwar_captcha.phrase_builder'] = new \Gregwar\Captcha\PhraseBuilder();
